name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image(Glassfish 6.0)
        run: |
          cd ./docker/glassfish6
          docker build -t hantsy/glassfish6:latest -f Dockerfile .
          
      - name: Test and Run Docker Image(Glassfish 6.0)
        run: |    
          docker run -d -p 4848:4848 -p 8080:8080 hantsy/glassfish6:latest 
          docker ps -a 

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push hantsy/glassfish6:latest
